### PR TITLE
Make vanilla great again

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Removed and ignored node_modules and the Gemfile.lock file. Updated the gulp-sass dep. Remove redundant scss files. Update css paths in the header.

## QA
- Run `gulp`
- Check there are no errors
- Open the server address to see the page

### CODE REVIEW

**Comment by nottrobin** [comment]
@anthonydillon you're supposed to keep Gemfile.lock in the repisitory - http://stackoverflow.com/questions/4151495/should-gemfile-lock-be-included-in-gitignore/4151540#4151540

**Comment by WillMoggridge** [comment]
I'm a bit worried about all this in the history, I would much prefer if this wasn't there.

**Comment by nottrobin** [comment]
I second @WillMoggridge's point. We should tidy up the repository at some point. Or right away, if anyone has time.

**Comment by pmahnke** [comment]
I am happy to refresh the whole thing... but should we get this PR merged first?

**Comment by nottrobin** [comment]
@pmahnke it has been :)

**Comment by pmahnke** [comment]
@nottrobin this was just a merge into my branch... not the back into master https://github.com/canonical-websites/design.ubuntu.com/pull/10

**Comment by WillMoggridge** [comment]
Items like this are much easier to remove in personal branches than upstream.

It has been merged into a feature branch so we can rebase it and remove it before going to master but we should definitely do this before it is merged straight into master. Then we can avoid changing the history which I really want to avoid. This can also be done by making sure we rebase in the pull request, and not merge.

**Pull request merged**
