### PR TITLE
Implement new font interaction

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Created a `design-p-font-tester` pattern
- Upgraded `vanilla-brochure-theme` to `1.0.4`
- Build the markup for the font tester
- Created a CSS only interaction
- Remove font-js from the codebase

## QA
- Pull down this branch
- Run:
```bash
bundle install
rm -rf node_modules
npm i
bundle exec jekyll serve
```
- Go to http://127.0.0.1:4000/font/
- Check that the font interaction works
- Check on small screens

## Details
Card: https://trello.com/c/s4U9fHLV

### CODE REVIEW

**Comment by pmahnke** [comment]
@anthonydillon I have noticed that some combinations do not result in a change in the sample, like condensed doesn't change font-size and mono-space doesn't have light and medium weights?

I think the first might be a bug... the second a font issue?

**Comment by anthonydillon** [comment]
Odd, condensed changes font-size for me.

Mono does not support light font. I was going to disable options that are
not available but wasn't sure if we want too.

**Comment by anthonydillon** [comment]
If you get a min today, lets try it out on your computer. @pmahnke

**Review by pmahnke — APPROVED** [review]
works... excellent

**Pull request merged**
